name: Nightly Build

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Get Kube Config
        run: |
          echo 'KUBE_CONFIG<<EOF' >> $GITHUB_ENV
          cat kube_config >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
        
      - name: Delete Cargo Tracker Deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ env.KUBE_CONFIG }}
        with:
          args: delete -f cargo-tracker.yml
        continue-on-error: true        
        
      - name: Delete PostgreSQL Deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ env.KUBE_CONFIG }}
        with:
          args: delete -f postgres.yml
        continue-on-error: true
        
      - name: Create PostgreSQL Deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ env.KUBE_CONFIG }}
        with:
          args: create -f postgres.yml
      
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean package -Pcloud -DpostgreSqlJdbcUrl="jdbc:postgresql://postgres:5432/postgres?user=postgres&amp;password=postgres" --file pom.xml
        
      - name: Login to DockerHub
        run: docker login -u rezarahman -p gemini6
        
      - name: Build Docker image
        run: docker build -t rezarahman/cargo-tracker:v2.1-SNAPSHOT .
        
      - name: Publish Docker image
        run:  docker push rezarahman/cargo-tracker:v2.1-SNAPSHOT
        
      - name: Create Cargo Tracker Deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ env.KUBE_CONFIG }}
        with:
          args: create -f cargo-tracker.yml